Item events and router restructuring
project-fika/Fuyu pull request #64
Opened 2024-10-05 20:03 UTC by nexus4880

# Item Events
I have added some of the events that I found drudging through the assembly.
There are more than likely more that I will add if I come across.
The code within the added controllers works well enough to move the items though I feel it may be too easy? I'm not so sure it is correct.
I have left some debug logs in. I have asked that these stay until we add proper logging.

# Routers
The way routers work now is:
A controller will be ran and is in charge of what it matches given a context.

```
IRouterController<TContext> where TContext : IRouterContext
{
	Task RunAsync(TContext context);
	bool IsMatch(TContext context);
}
```

`IRouterContext` is a tag to enforce custom types on contexts.

There are 2 ways to use a router.
- Creating your own class: `MyRouter : Router<MyController, MyContext>`
- Using the `Router` class directly : `Router<MyController, MyContext>`

`Router` only *needs* to be inherited if one plans to override `RouteAsync`. We do this in `WsRouter` as we need to call `InitializeAsync` on the `WsController` before we `RunAsync`. **It is highly recommended to create a custom type for your router.**

2024-10-05 20:10 UTC, Lacyway submitted a review, later dismissed

2024-10-07 11:41 UTC, seionmoya requested changes
Some smaller stuff, we're still discussing the overall design in private.

2024-10-07 16:29 UTC, seionmoya requested changes

2024-10-07 17:17 UTC, seionmoya submitted a review, later dismissed

2024-10-07 17:53 UTC, seionmoya approved these changes

2024-10-07 17:53 UTC, merged